config/routes.rb
VaccineManager::Application.routes.draw do
  resources :schedules
  
  root :to => 'schedules#index'
  
  get "manager/timetable"

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  
  Templates= [ 'U.S. CDC 2011', 'Custom' ]
  
  has_many :vaccines, dependent: :destroy, order: :position
  has_many :doses, through: :vaccines
  accepts_nested_attributes_for :vaccines, allow_destroy: true
 
  attr_accessible :person_name, :date_of_birth, :date_of_birth_year, :template, :notes, :vaccines_attributes
  
  validates :person_name, presence: true, uniqueness: true
  validates :date_of_birth, presence: true
  validates :date_of_birth_year, presence: true, numericality: { only_integer: true }
  validates :template, presence: true, inclusion: { in: Templates }
  validates_associated :vaccines
  
  def date_of_birth_year
    @date_of_birth_year ||= self.date_of_birth.year
  end

  def date_of_birth_year=(year)
    @date_of_birth_year= year
  end
  
  def dose_months
    dose_months= SortedSet.new()
    
    self.doses.each do |dose|
      dose_months << dose.months_scheduled_from_date_of_birth
      dose_months << (dose.months_scheduled_from_date_of_birth + dose.administration_window_in_months - 1)
    end
    
    return dose_months
  end
  
 # TBD: Should be protected or folded into overridden new method?
  def template_vaccines
    case self.template
      when Templates[0] # U.S. CDC 2011
        return [ 
{ position: 1, name: 'Hepatitis B', short_name: 'HepB', doses_attributes: [
{ months_scheduled_from_date_of_birth: 0, administration_window_in_months: 1 }, 
{ months_scheduled_from_date_of_birth: 1, administration_window_in_months: 2 }, 
{ months_scheduled_from_date_of_birth: 6, administration_window_in_months: 13 } ] },
{ position: 2, name: 'Rotavirus', short_name: 'RV', doses_attributes: [
{ months_scheduled_from_date_of_birth: 2, administration_window_in_months: 1 }, 
{ months_scheduled_from_date_of_birth: 4, administration_window_in_months: 1 }, 
{ months_scheduled_from_date_of_birth: 6, administration_window_in_months: 1 } ] },
{ position: 3, name: 'Diphtheria, Tetanus, & acellular Pertussis', short_name: 'DTaP', doses_attributes: [
{ months_scheduled_from_date_of_birth: 2, administration_window_in_months: 1 }, 
{ months_scheduled_from_date_of_birth: 4, administration_window_in_months: 1 }, 
{ months_scheduled_from_date_of_birth: 6, administration_window_in_months: 1 },
{ months_scheduled_from_date_of_birth: 15, administration_window_in_months: 3 },
{ months_scheduled_from_date_of_birth: 4*12, administration_window_in_months: 3*12 } ] }, 
{position: 4, name: 'Haemophilus influenzae type b', short_name: 'Hib', doses_attributes: [
{ months_scheduled_from_date_of_birth: 2, administration_window_in_months: 1 }, 
{ months_scheduled_from_date_of_birth: 4, administration_window_in_months: 1 }, 
{ months_scheduled_from_date_of_birth: 6, administration_window_in_months: 1 },
{ months_scheduled_from_date_of_birth: 12, administration_window_in_months: 4 } ] }, 
{position: 5, name: 'Pneumococcal conjugate vaccine, 13-valent', short_name: 'PCV13', doses_attributes: [
{ months_scheduled_from_date_of_birth: 2, administration_window_in_months: 1 }, 
{ months_scheduled_from_date_of_birth: 4, administration_window_in_months: 1 }, 
{ months_scheduled_from_date_of_birth: 6, administration_window_in_months: 1 },
{ months_scheduled_from_date_of_birth: 12, administration_window_in_months: 4 } ] }, 
{position: 6, name: 'Inactivated poliovirus vaccine', short_name: 'IPV', doses_attributes: [
{ months_scheduled_from_date_of_birth: 2, administration_window_in_months: 1 }, 
{ months_scheduled_from_date_of_birth: 4, administration_window_in_months: 1 }, 
{ months_scheduled_from_date_of_birth: 6, administration_window_in_months: 13 },
{ months_scheduled_from_date_of_birth: 4*12, administration_window_in_months: 3*12 } ] },
#{position: 7, name: 'Trivalent inactivated influenza vaccine', short_name: 'TIV', doses_attributes: [
#{ months_scheduled_from_date_of_birth: 6, administration_window_in_months: 12 },
#{ months_scheduled_from_date_of_birth: 18, administration_window_in_months: 12 } ] }, 
#{position: 8, name: 'Live, attenuated influenza vaccine', short_name: 'LAIV', doses_attributes: [
#{ months_scheduled_from_date_of_birth: 30, administration_window_in_months: 12 }, 
#{ months_scheduled_from_date_of_birth: 42, administration_window_in_months: 12 },
#{ months_scheduled_from_date_of_birth: 54, administration_window_in_months: 12 },
#{ months_scheduled_from_date_of_birth: 66, administration_window_in_months: 12 },
#{ months_scheduled_from_date_of_birth: 78, administration_window_in_months: 12 } ] },
{position: 7, name: 'Measles, Mumps, & Rubella', short_name: 'MMR', doses_attributes: [
{ months_scheduled_from_date_of_birth: 12, administration_window_in_months: 4 }, 
{ months_scheduled_from_date_of_birth: 4*12, administration_window_in_months: 3*12 } ] }, 
{position: 8, name: 'Varicella', short_name: 'Varicella', doses_attributes: [
{ months_scheduled_from_date_of_birth: 12, administration_window_in_months: 4 }, 
{ months_scheduled_from_date_of_birth: 4*12, administration_window_in_months: 3*12 } ] }, 
{position: 9, name: 'Hepatitis A', short_name: 'HepA', doses_attributes: [
{ months_scheduled_from_date_of_birth: 12, administration_window_in_months: 4 },
{ months_scheduled_from_date_of_birth: 23, administration_window_in_months: 1 } ] } ]
        
      when Templates[1] # Custom
        return []

      else
        puts "MESSAGE: Invalide template (" + template.to_s + ") detected."
        return []
    end
  end
  
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
    
  before_filter :load_date_of_birth_year, only: [ :create, :update ]
  
  # GET /schedules
  # GET /schedules.json
  def index
    @schedules= Schedule.all
    @subtitle= ": Schedules Listing"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schedules }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show    
    @schedule= Schedule.find(params[:id])
    @subtitle= ": Viewing Schedule for " << @schedule.person_name

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    @schedule= Schedule.new({ date_of_birth: Date.today, date_of_birth_year: Date.today.year })
    @subtitle= ": Entering New Schedule"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule= Schedule.find(params[:id])
    @subtitle= ": Editing Schedule for " << @schedule.person_name
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule= Schedule.new(params[:schedule])
    @schedule.vaccines.build(@schedule.template_vaccines)      
       
    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render json: @schedule, status: :created, location: @schedule }
      else
        format.html { render action: "new" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    @schedule= Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule= Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :ok }
    end
  end
  
  protected
    
  def load_date_of_birth_year
    params[:schedule]["date_of_birth(1i)"]= params[:schedule][:date_of_birth_year]
  end
  
end

app/helpers/schedules_helper.rb
module SchedulesHelper
    
  def dose_colspan(dose, month)
    dose_colspan= 0
    @schedule.dose_months.each do |month|
      dose_colspan+= 1 if (dose.months_scheduled_from_date_of_birth <= month && 
month <= dose.months_scheduled_from_date_of_birth + dose.administration_window_in_months - 1)
    end
    
    return dose_colspan
  end
  
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |schedule_form| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= schedule_form.select(:template, options_for_select(Schedule::Templates, selected: Schedule::Templates[0], disabled: Schedule::Templates[1..Schedule::Templates.length-1] )) %> 0&ndash;6 year immunization schedule for <%= schedule_form.text_field :person_name, size: 40, placeholder: "Enter person name"  %> born on <%= schedule_form.date_select :date_of_birth, order: [:day, :month] %><%= schedule_form.text_field :date_of_birth_year, size: 10, placeholder: "Year (YYYY)" %>
  </div>
  <div class="field">
    <table>
      <% unless @schedule.new_record? %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
          <th class="table_corner_header_left_cell">Vaccine &darr;</th><th class="table_corner_header_right_cell">Age &rarr;</th>
          <% @schedule.dose_months.each do |month| %>
            <th class="table_top_header"><%= month < 24 ? month.to_s + " M" : month.divmod(12).first.to_s + " Y, " + month.divmod(12).last.to_s + " M" %></th>
          <% end %>
        </tr>
        <%= schedule_form.fields_for :vaccines do |vaccine_fields| %>
          <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
            <th rowspan="3", colspan="2", class="table_side_header"><%= vaccine_fields.object.name %></th>
            <% @schedule.dose_months.each do |month| %>
              <% flag= false; vaccine_fields.object.doses.each do |dose| %>
                <% if dose.months_scheduled_from_date_of_birth == month %>
                  <th colspan="<%= dose_colspan(dose, month) %>", class="dose_short_name"><%= vaccine_fields.object.short_name %></th>
                  <% flag= true; break %>
                <% elsif (dose.months_scheduled_from_date_of_birth < month) && (month < dose.months_scheduled_from_date_of_birth + dose.administration_window_in_months) %>
                  <% flag= true; break %>
                <% end %>
              <% end %>
              <% unless flag %>
                <td class="dose_short_name">&nbsp;</td>
              <% end %>
            <% end %>
          </tr>
          <tr class="<%= current_cycle %>">
            <% @schedule.dose_months.each do |month| %>
              <% flag= false; vaccine_fields.object.doses.each do |dose| %>
                <% if dose.months_scheduled_from_date_of_birth == month %>
                  <td colspan="<%= dose_colspan(dose, month) %>", class="dose_due">due: <%= (l(dose.vaccine.schedule.date_of_birth.advance(months: dose.months_scheduled_from_date_of_birth), format: :dose) + "&ndash;" + l(dose.vaccine.schedule.date_of_birth.advance(months: dose.months_scheduled_from_date_of_birth + dose.administration_window_in_months, days: -1), format: :dose)).html_safe %></td>
                  <% flag= true; break %>
                <% elsif (dose.months_scheduled_from_date_of_birth < month) && (month < dose.months_scheduled_from_date_of_birth + dose.administration_window_in_months) %>
                  <% flag= true; break %>
                <% end %>
              <% end %>
              <% unless flag %>
                <td class="dose_due">&nbsp;</td>
              <% end %>
            <% end %>
          </tr>
          <tr class="<%= current_cycle %>">
            <% @schedule.dose_months.each do |month| %>
              <% flag= false; vaccine_fields.object.doses.each do |dose| # TBD: Why doesn't "vaccine_fields.fields_for :doses do |dose_fields| " work directly? %>
                <% if dose.months_scheduled_from_date_of_birth == month %>
                  <%= vaccine_fields.fields_for :doses, dose do |dose_fields| %>
                    <td colspan="<%= dose_colspan(dose, month) %>", class="dose_given">given: <%= dose_fields.date_select :date_administered, use_short_month: true, start_year: @schedule.date_of_birth.year, end_year: @schedule.date_of_birth.year + 8, order: [ :day, :month, :year ], prompt: { day: '-d-', month: '-m-', year: '-y-' } %></td>
                  <% end %>
                  <% flag= true; break %>
                <% elsif (dose.months_scheduled_from_date_of_birth < month) && (month < dose.months_scheduled_from_date_of_birth + dose.administration_window_in_months) %>
                  <% flag= true; break %>
                <% end %>
              <% end %>
              <% unless flag %>
                <td class="dose_given">&nbsp;</td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      <% end %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td colspan="2", class="notes">Notes</td><td colspan="<%= @schedule.dose_months.length.to_s %>"><%= schedule_form.text_area :notes, cols: 120, rows: 3, placeholder: "Enter optional notes" %></td>
      </tr>
    </table>
  </div>
  <div class="actions">
    <%= schedule_form.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h2>Vaccine Manager is a web application being developed to plan vaccination schedules and to record dose administration. This is for demonstration purposes only, and currently there is no privacy or permanency of the data entered into this application.</h2>

<table>
  <tr>
    <th>Person Name</th>
    <th>Birthday</th>
    <th>Template</th>
    <th>Notes</th>
    <th colspan="3">Action</th>
  </tr>

<% @schedules.each do |schedule| %>
  <tr>
    <td><%= schedule.person_name %></td>
    <td><%= schedule.date_of_birth %></td>
    <td><%= schedule.template %></td>
    <td><%= truncate(schedule.notes, length: 80) %></td>
    <td><%= link_to 'Show', schedule %></td>
    <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
    <td><%= link_to 'Destroy', schedule, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= @schedule.template %></b> 0&ndash;6 year immunization schedule for <b><%= @schedule.person_name %></b> born on <b><%= l @schedule.date_of_birth %></b>
</p>
<p>
  <table>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <th class="table_corner_header_left_cell">Vaccine &darr;</th><th class="table_corner_header_right_cell">Age &rarr;</th>
      <% @schedule.dose_months.each do |month| %>
        <th class="table_top_header"><%= month < 24 ? month.to_s + " M" : month.divmod(12).first.to_s + " Y, " + month.divmod(12).last.to_s + " M" %></th>
      <% end %>
    </tr>
    <% @schedule.vaccines.each do |vaccine| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <th rowspan="3", colspan="2", class="table_side_header"><%= vaccine.name %></th>
        <% @schedule.dose_months.each do |month| %>
          <% flag= false; vaccine.doses.each do |dose| %>
            <% if dose.months_scheduled_from_date_of_birth == month %>
              <th colspan="<%= dose_colspan(dose, month) %>", class="dose_short_name"><%= vaccine.short_name %></th>
              <% flag= true; break %>
            <% elsif (dose.months_scheduled_from_date_of_birth < month) && (month < dose.months_scheduled_from_date_of_birth + dose.administration_window_in_months) %>
              <% flag= true; break %>
            <% end %>
          <% end %>
          <% unless flag %>
            <td class="dose_short_name">&nbsp;</td>
          <% end %>
        <% end %>
      </tr>
      <tr class="<%= current_cycle %>">
        <% @schedule.dose_months.each do |month| %>
          <% flag= false; vaccine.doses.each do |dose| %>
            <% if dose.months_scheduled_from_date_of_birth == month %>
              <td colspan="<%= dose_colspan(dose, month) %>", class="dose_due">due: <%= (l(dose.vaccine.schedule.date_of_birth.advance(months: dose.months_scheduled_from_date_of_birth), format: :dose) + "&ndash;" + l(dose.vaccine.schedule.date_of_birth.advance(months: dose.months_scheduled_from_date_of_birth + dose.administration_window_in_months, days: -1), format: :dose)).html_safe %></td>
              <% flag= true; break %>
            <% elsif (dose.months_scheduled_from_date_of_birth < month) && (month < dose.months_scheduled_from_date_of_birth + dose.administration_window_in_months) %>
              <% flag= true; break %>
            <% end %>
          <% end %>
          <% unless flag %>
            <td class="dose_due">&nbsp;</td>
          <% end %>
        <% end %>
      </tr>
      <tr class="<%= current_cycle %>">
        <% @schedule.dose_months.each do |month| %>
          <% flag= false; vaccine.doses.each do |dose| %>
            <% if dose.months_scheduled_from_date_of_birth == month %>
              <td colspan="<%= dose_colspan(dose, month) %>", class="dose_given">given: <%= l(dose.date_administered, format: :dose) unless dose.date_administered.nil? %></td>
              <% flag= true; break %>
            <% elsif (dose.months_scheduled_from_date_of_birth < month) && (month < dose.months_scheduled_from_date_of_birth + dose.administration_window_in_months) %>
              <% flag= true; break %>
            <% end %>
          <% end %>
          <% unless flag %>
            <td class="dose_given">&nbsp;</td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td colspan="2", class="notes">Notes</td><td colspan="<%= @schedule.dose_months.length.to_s %>", class="notes"><%= @schedule.notes %></td>
    </tr>
  </table>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>